[[ch01-what-will-be-used]]
== Everything we are going to use

In this chapter I am going to introduce you to all the tools and online resources that will be used in this book, so you could go ahead and be able to make a comparison for the online services and make informed choices later. I do not want to convince you for any specific one, I will demonstrate that the same recipes can run with almost no modification in any of them, so what you learn is portable, not vendor locked.

=== Tools

==== MicroK8S

https://bit.ly/3pZ5yeP[**MicroK8s**] was initially designed to be used as a small quick Kubernetes cluster for local development. One of the core ideas of containers was immutability, so, what you are running locally, will run identically out there in the production setup. It has evolved to a production grade solution that can run single or multi-machine clusters, on x86-64 and arm64 platforms.

I became a fan of MicroK8s the moment I discovered that I could experiment with it on a Raspberry Pi 4 I had, and it simply impressed me that in a few minutes I had Kubernetes available and I could just start a WordPress experiment I was working on without any changes.

==== Docker

While http://j.mp/2NtQaZx[**Docker**] is an alternative to Kubernetes, it is much easier to use for local development and could be preferred at times in production. We will see how it can help us with WordPress development in a later chapter.

==== Multipass

https://multipass.run[**Multipass**] is an application that runs on Windows, MacOS, Linux distributions and allows simple and quick provisioning of local virtual machines. While there are alternatives, if you have never had to work with virtual machines locally, you will enjoy it's simplicity. If you already have any other preference, things should work our almost the same, just ensure you will have a minimal ubuntu any recent LTS version up and running.

==== Visual Studio Code

http://j.mp/2NqWSzu[**Visual Studio Code**] is one of the few code editors and light integrated development environments capable of handling remote or containerized projects. While all things in this book could be done with other code editors, especially everything from the command line, I will use it for the benefit of beginners to help them learn faster.

==== Github

https://github.com[**Github**] will be my choice to keep a repository for my cluster's manifests and other provisioning code. By getting a good understanding of everything, with it you can even recover from a complete failure, even with data if that can be automated on first init of a resource with a backup available where is expected.

=== Cloud Providers

==== Hetzner

I will use https://bit.ly/3cLf8hH[**Hetzner**] to exemplify things on real cloud servers. As using real online instances involves a cost, I have chosen one of the cheapest that is still very reliable as a public cloud provider. Although it does not offer many managed services compared to others, my goal in this book is to teach you how to do things without being locked into a public cloud vendor, to be able to move the very next day if such a decision need be taken.
