[[ch03-first-experiment]]
== First experiment (local)

Let's try out a first experiment locally, with no money spent on cloud resources, in order to learn how to work locally using MicroK8s.

For my local setup, I'm going to use a PC, with Windows 11 Pro Edition and Multipass. Alternatively, any virtualization solution you enjoy can be used with the goal to get a virtual machine with some specific networking setup, which is close to what is in the public cloud.

NOTE: For Windows 10 and 11 Home users of WSL2 or Docker for Windows, ensure to have WSL2 and Docker first installed and working. At the moment I've wrote this chapter, Multipass was not able yet to use the low level Hyper-V platform and still requires Virtualbox; Virtualbox installs it's virtualization module if it can't find Hyper-V already enabled in Windows, or if installed after it is enabled, it will use it instead.

NOTE: Alternative for Raspberry Pi fans, use the latest Ubuntu 20.04 or 22.04 server image for Raspberry Pi and after you boot it continue from the `snap install` command below. If running from an sd card, you will need to be a lot more patient while background operations happen; using a UASP compatible SSD on USB 3.0 port will provide really decent performance.

The next steps will be done in a terminal, so open your prefered terminal, and for simplicity keep it in your personal directory.

If you never setup ssh on your computer, this step is required, as you will need it when working with remote virtual machines as well. Simply run `ssh-keygen` and hit enter at each question. If you want a setup with more control, read the official help on https://man.openbsd.org/ssh-keygen[OpenSSH] or a simple guide on https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent[GitHub's Docs].

Copy in the clipboard your public key:

* Windows `clip < .ssh\id_rsa.pub`
* MacOS `pbcopy < ~/.ssh/id_rsa.pub`
* Linux `cat ~/.ssh/id_rsa.pub`, then select and copy the contents using CTRL+SHIFT+C

NOTE: the name of the key can be different, in case that your ssh default application is set to another algorithm, like *ed25519*. You can see all the files by typing either `ls -l .ssh/` on MacOS and Linux or `dir .ssh\` on Windows.

Open an editor, like Visual Studio Code, and create a file, in your user directory, named cloud-init-wpk8s.yaml and insert the text from the following template, replacing the ssh-public-key-text string with your public key.

[source,yaml,linenums]
----
---
ssh_authorized_keys:
- ssh-public-key-text
----

Open your prefered terminal and run the following to create a virtual machine to experiment with:

`multipass launch --name wpk8s --cpus 1 --mem 2G --disk 10G focal --cloud-init cloud-init-wpk8s.yaml`

and hit `Enter`.

If this is the first time it runs, it will download the official Ubuntu Linux, 20.04 focal image, and the normal process of creating and booting the machine will continue, probably taking a couple of minutes, depending on internet download speed and computing power of your device.

NOTE: You can omit `focal` from the command to experiment with a more recent LTS if one has been published since this book edition release.

Next, I will connect Visual Studio Code to the virtual machine, to be able to write the configuration files easier. Add the https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh[Remote SSH extension] to Visual Studio Code, searching for it in the Extensions section of it. Once installed, you can access the new Remote Explorer section. Ensure SSH Targets is selected in the top dropdown, in case you have multiple Remote extensions.

Let's grab the instance IP address: `multipass info wpk8s`. You will spot the IP address.

In Visual Studio Code hit the plus on Remote Explorer and add a new entry similar to this one, ensuring you use the IP address you previously found: `ssh ubuntu@172.24.112.62`. If asked about ssh config location, I use the default in my user directory, but fill free to experiment with alternative locations if you must do it.

Right click on the new listed entry and click *Connect to host in Current Window*.

You might be get a question about what is host type, choose Linux, and after it finishes installing the required support in the virtual machine, you might get probably a notification that it's type has been stored into some configuration.

Hit *CTRL+`* on Windows or Linux or *CMD+`* on MacOS and use the built in prompt for the rest of the tutorial.

To get MicroK8s up and running, all we need is to run this:

`sudo snap install microk8s --classic --channel=1.23/stable`

This will download all it needs from the official online location that Canonical manages, install the necesarry services and run the Kubernetes cluster.

NOTE: You can omit `stable/1.23` to use a more recent release if one has been published since this book edition release.

Next run `sudo microk8s status -w` and within a few seconds, you will see the ready status of the cluster.

We can now enable the minimal addons that we need to work with WordPress:

`sudo microk8s enable dns storage ingress`.

*DNS* is the addon that will allow micro-services to be able to communicate in the internal networks the Kubernetes cluster will handle by using hostnames. In our first example, the `wordpress` service will be able to use `wordpress-mysql` database service, using the hostname with identical name, making life easier when _baking recipes_ for our WordPress websites.

*STORAGE* is MicroK8s local storage addon, that enables creation of local volumes to hold permanent data. For a single node, it is one quick way of getting the cluster with permanent storage for containers.

*INGRESS* is a service that runs Nginx, the minimal official Kubernetes supported ingress. It will work as a proxy balancer, that understands virtual hosting and allows us to set many rules we would like to be handled outside of our WordPress services. As our WordPress main service could be scaled up to multiple instances to support a high amount of traffic, the INGRESS service is a key component. Also, it allows us to easily run an unlimited amount of WordPress websites in our cluster, depending on it's size.

In Visual Studio Code, you will need to open a folder to be able to work with files. Ensure you are in Explorer section and click on Open Folder button. You can click OK for the default `/home/ubuntu`.

In the Visual Studio Code's Workspace, create a folder, name it `wordpress` and within it create 3 files:

* `kustomization.yaml`
* `mysql.yaml`
* `wordpress-volume.yaml`
* `wordpress.yaml`

For each one, insert the following content:

.https://gist.github.com/madalinignisca/93339ec774b00bc5589b3a45fc968eb5#file-kustomization-yaml[kustomization.yaml]
[source,yaml,linenums]
----
---
secretGenerator:
- name: mysql-root-pass
  literals:
  - password=password123
- name: mysql-user
  literals:
  - user=wordpress
- name: mysql-pass
  literals:
  - password=wordpress
- name: mysql-database
  literals:
  - database=wordpress
resources:
  - mysql.yaml
  - wordpress.yaml
----

.https://gist.github.com/madalinignisca/93339ec774b00bc5589b3a45fc968eb5#file-mysql-yaml[mysql.yaml]
[source,yaml,linenums]
----
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  serviceName: wordpress-mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mariadb:10.6
        name: mysql
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-database
              key: database
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MARIADB_AUTO_UPGRADE
          value: "true"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: wordpress-mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: wordpress-mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
----

.https://gist.github.com/madalinignisca/93339ec774b00bc5589b3a45fc968eb5#file-wordpress-volume-yaml[wordpress-volume.yaml]
[source,yaml,linenums]
----
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
----

.https://gist.github.com/madalinignisca/93339ec774b00bc5589b3a45fc968eb5#file-wordpress-yaml[wordpress.yaml]
[source,yaml,linenums]
----
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  rules:
  - host: wordpress.k8s
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: wordpress
              port:
                number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup wordpress-mysql; do echo waiting for mysql; sleep 2; done;']
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: user
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-database
              key: database
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress
          mountPath: /var/www/html
      volumes:
        - name: wordpress
----

Go back to the terminal (`Ctrl+\``), if you are not in the machine's shell, run `vagrant ssh`, and now change directory to our shared workspace, in the WordPress folder: `cd /vagrant/wordpress`. Run

`sudo microk8s kubectl apply -f ./wordpress-volume.yaml`

`sudo microk8s kubectl apply -k ./`

This commands will instruct Kubernetes to load the _recipe_ and create all required resources, add a secret for mysql password, start the services and create an ingress entry to allow outside access to our WordPress website.

`sudo microk8s kubectl get all`

With this command, you can check the status of all resources. When all is provisioned, you should see something like:

----
ubuntu@wpk8s:~/wordpress$ sudo microk8s kubectl get all
NAME                             READY   STATUS    RESTARTS   AGE
pod/wordpress-mysql-0            1/1     Running   0          20m
pod/wordpress-6d56f69645-gvbqd   1/1     Running   0          20m

NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/kubernetes        ClusterIP   10.152.183.1    <none>        443/TCP    75m
service/wordpress         ClusterIP   10.152.183.49   <none>        80/TCP     20m
service/wordpress-mysql   ClusterIP   None            <none>        3306/TCP   20m

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/wordpress   1/1     1            1           20m

NAME                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/wordpress-6d56f69645   1         1         1       20m

NAME                               READY   AGE
statefulset.apps/wordpress-mysql   1/1     20m
----

Next, let's discover the local ip assigned to our virtual machine, so we can put it in our host system's hosts file. Run `ip addr | grep eth0` in the shell and look for an IP similar to `172.24.112.62`. Multipass by default assigns an IP address prefixed like `172.24.112.`.

In Windows, press Start, type `cmd`, right click on the result and click `Run as administrator` and click `Yes` to allow higher privileges. In the opened prompt, run `cd drivers\etc` and then `notepad hosts`. This will open Notepad with the hosts file opened. Somewhere at the end of
the file add the following line, but *make sure to substitute the IP you identified previously*.

`172.24.112.62 wordpress.k8s`

Open a browser and load `http://wordpress.k8s`. It should load the WordPress installation page. Do the installation, post something, including an image and let's move to next step.

Let's do an experiment. Let's delete our WordPress installation.

`sudo microk8s kubectl delete -k ./`

Try to reload the website in the browser. 504 or 404, eventually sticking to 404. As expected, we deleted the application. You can also use `sudo microk8s kubectl get all` to check how they get destroyed.

Let's bring it back:

`sudo microk8s kubectl apply -k ./` `sudo microk8s kubectl get all`

When all are ready, faster than the first time, in the browser, we can see the website once again, so our previous deletion is undone!

The trick was in how we have declared volume allocation and the type of resource the applications are. In terms of containers, our setup is composed from two applications until this moment, one the WordPress container that runs Apache and PHP embeded as a module, serving from a dedicated volume that has WordPress installed when launched for the first time, and another application, our MySQL compatible service, running MariaDB, which also has an allocated permanent volume.

We defined our mysql instance as StatefulSet, to protect us in case of deleting them by mistake, allowing us to recreate it all in a matter of seconds. Also, we declared the wordpress volume separate, and to remove it we would need to explicitly delete it.

Probably a lot was done above and you might be confused about what are the configurations for all the things, but you will learn about them within the following chapters in detail.

Let's proceed to the next chapter, where we will create our first MicroK8s Kubernetes cluster out in the public cloud.
